version: "3.8"

services:
  backend:
    build:
      context: ./chatbot-backend
    ports:
      - "8080:8080"
    environment:
      PORT: 8080

  frontend:
    build:
      context: ./chatbot-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
